
version: '2.1'

volumes:
    shered-ros-bin:


services:

  roscore:
  
    build: ./ros
    environment: 
       - UDEV=1
       - ROS_HOSTNAME=roscore
       - ROS_MASTER_URI=http://roscore:11311
       
    links: 
      - rosboard
      - lidar
    volumes:
      - shered-ros-bin:/opt/ros/noetic
      
  lidar:
    image: cristidragomir97/rplidar:latest
    privileged: true
    environment: 
       - UDEV=1
       - ROS_HOSTNAME=lidar
       - ROS_MASTER_URI=http://roscore:11311
    devices:
      - "/dev:/dev"
    volumes:
      - shered-ros-bin:/opt/ros/noetic


  rosboard:
    image: cristidragomir97/rosboard:latest
    environment: 
       - ROS_HOSTNAME=rosboard
       - ROS_MASTER_URI=http://roscore:11311
     ports:
      - "8080:80"
    volumes:
      - shered-ros-bin:/opt/ros/noetic
 
#    build: ./hectorslam
#    network_mode: host
#    environment: 
##      - UDEV=1
 #   devices:
 #     - "/dev:/dev"

  
