
version: '2.1'

volumes:
    shered-ros-bin:


services:

  roscore:
  
    build: ./ros
    environment: 
       - UDEV=1
       - ROS_HOSTNAME=roscore
       - ROS_MASTER_URI=http://roscore:11311
    links: 
      - rosboard
      - hectorslam
      - lidar
    volumes:
      - shered-ros-bin:/opt/ros/noetic
      
  lidar:
    image: cristidragomir97/rplidar:latest
    privileged: true
    environment: 
       - UDEV=1
       - ROS_HOSTNAME=lidar
       - ROS_MASTER_URI=http://roscore:11311
    devices:
      - "/dev:/dev"
    volumes:
      - shered-ros-bin:/opt/ros/noetic


  rosboard:
    build: ./rosboard
    environment: 
       - ROS_HOSTNAME=rosboard
       - ROS_MASTER_URI=http://roscore:11311
    ports:
      - "8888:8888"
    volumes:
      - shered-ros-bin:/opt/ros/noetic
 
  hectorslam: 
    build: ./hectorslam
    volumes:
      - shered-ros-bin:/opt/ros/noetic
    environment: 
      - ROS_HOSTNAME=hectorslam
      - ROS_MASTER_URI=http://roscore:11311

  
