
version: '2.1'

volumes:
    ros-bin:
    boost-bin:

services:
  roscore:
    build: ./ros
    environment: 
       - UDEV=1
       - ROS_HOSTNAME=roscore
       - ROS_MASTER_URI=http://roscore:11311
    links: 
      - rosboard
      - camera
    ports:
      - "11311:11311"
    volumes:
      - ros-bin:/opt/ros/noetic
      - boost-bin:/usr/include/boost

  camera:
    image: cristidragomir97/rpicam
    privileged: true
    environment: 
       - ROS_HOSTNAME=camera
       - ROS_MASTER_URI=http://roscore:11311
    volumes:
      - ros-bin:/opt/ros/noetic
      - boost-bin:/usr/include/boost

  rosboard:
    build: ./rosboard
    environment: 
       - ROS_HOSTNAME=rosboard
       - ROS_MASTER_URI=http://roscore:11311
    ports:
      - "8888:8888"
    volumes:
      - ros-bin:/opt/ros/noetic
      - boost-bin:/usr/include/boost
