
version: '2.1'

volumes:
    shered-ros-bin:


services:

  roscore:
    build: ./ros
    environment: 
        - UDEV=1
        - ROS_MASTER_URI=http://roscore:11311
    volumes:
      - shered-ros-bin:/opt/ros/noetic
    labels:
      io.balena.features.balena-api: '1'
      io.balena.features.supervisor-api: 1
      
  lidar:
    image: cristidragomir97/rplidar:latest
    privileged: true
    environment: 
       - UDEV=1
       - ROS_HOSTNAME=lidar
       - ROS_MASTER_URI=http://roscore:11311
    devices:
      - "/dev:/dev"
    volumes:
      - shered-ros-bin:/opt/ros/noetic
    labels:
      io.balena.features.balena-api: '1'
      io.balena.features.supervisor-api: 1

  rosboard:
    image: cristidragomir97/rosboard:latest
    environment: 
       - ROS_HOSTNAME=rosboard
       - ROS_MASTER_URI=http://roscore:11311
    volumes:
      - shered-ros-bin:/opt/ros/noetic
    ports:
      - "8080:80"
    labels:
      io.balena.features.balena-api: '1'
      io.balena.features.supervisor-api: 1

#    build: ./hectorslam
#    network_mode: host
#    environment: 
##      - UDEV=1
 #   devices:
 #     - "/dev:/dev"

  
