version: '2.1'

volumes:
    ros-bin: 
    boost-lib:
    python-packages:

services:
  ros-core:
    image: cristidragomir97/ros-core
    environment: 
       - UDEV=1
       - ROS_HOSTNAME=ros-core
       - ROS_MASTER_URI=http://ros-core:11311
    links: 
      - ros-board
      - ros-io 
    ports:
      - "11311:11311"
    volumes:
      - ros-bin:/opt/ros/noetic
      - boost-lib:/usr/include/boost

  ros-board:
    depends_on:
      - ros-core
    image: cristidragomir97/ros-board
    environment: 
       - ROS_HOSTNAME=ros-board
       - ROS_MASTER_URI=http://ros-core:11311
    ports:
      - "8888:8888"
    volumes:
      - ros-bin:/opt/ros/noetic

  ros-io:
    depends_on:
      - ros-core
    privileged: true
    image: cristidragomir97/ros-io
    environment: 
       - UDEV=1
       - ROS_HOSTNAME=ros-io
       - ROS_MASTER_URI=http://ros-core:11311
       - CONFIG_REPO=https://github.com/cristidragomir97/ep1-rc-car
    volumes:
      - ros-bin:/opt/ros/noetic
    devices:
      - "/dev:/dev"
     

  ros-camera:
    depends_on:
      - ros-core
    privileged: true
    image: cristidragomir97/ros-camera
    environment: 
       - UDEV=1
       - ROS_HOSTNAME=ros-camera
       - ROS_MASTER_URI=http://ros-core:11311
    volumes:
      - ros-bin:/opt/ros/noetic
      - boost-lib:/usr/include/boost
    devices:
      - "/dev:/dev"


#  ros-rplidar:
#    depends_on:
#      - ros-core
#    privileged: true
#    image: cristidragomir97/ros-rplidar
#    environment: 
#       - UDEV=1
#       - ROS_HOSTNAME=ros-rplidar
#       - ROS_MASTER_URI=http://ros-core:11311
#    volumes:
#      - ros-bin:/opt/ros/noetic
#    devices:
#      - "/dev:/dev"

  ros-joystick:
    depends_on:
      - ros-core
    privileged: true
    image: cristidragomir97/ros-joystick
    environment: 
       - ROS_HOSTNAME=ros-joystick
       - ROS_MASTER_URI=http://ros-core:11311
    volumes:
      - ros-bin:/opt/ros/noetic
      - boost-lib:/usr/include/boost
    devices:
      - "/dev:/dev"
    
