FROM cristidragomir97/hectorslam:latest

COPY mapping_default.launch /root/catkin_ws/src/rplidar_hector_slam/hector_slam/hector_mapping/launch/mapping_default.launch
COPY tutorial.launch /root/catkin_ws/src/rplidar_hector_slam/hector_slam/hector_slam_launch/launch/tutorial.launch



#   sh -c '. /opt/ros/noetic/setup.sh \
#    && . /root/catkin_ws/devel/setup.sh \
#    && roslaunch hector_slam_launch tutorial.launch'